language: python
python:
  - "3.7"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/econ-ark/HARK.git@master
# command to run tests
script:
  - pytest --nbval-lax notebooks/

